### ISSUE TITLE
what is happened?

### ISSUE THREAD

**Issue by mrKornWij** [cvg/Hierarchical-Localization#124]
in Localization. I've tested many different dataset. I have 5 queries for each dataset. some datasets could localize queries that I input them in but some datasets they're not and they shown the result like this(in the picture). what's really happened?

![image](https://user-images.githubusercontent.com/88375996/142715105-2ae7d654-ab2f-439e-8b0c-051ccce4b402.png)
![image](https://user-images.githubusercontent.com/88375996/142715115-d6efb0bc-b964-48c7-a2e7-a26adcc5278c.png)

**Comment by Skydes** [comment]
Image `q1.jpg` retrieved 5 images `d9xxxx.jpg` that are not part of the 3D model. The probable reason is that you called `pairs_from_retrieval` against against all images (query+references), or some references were hard to reconstruct and thus not included in the 3D model. In any case, to prevent this, you can specify the list of reference images as those of an existing 3D model using the flag `--db_model` instead of `--db_prefix` or `--db_list`.

**Comment by mrKornWij** [comment]
ัdo you mean that,  to fix this error. I don't need to use db_prefix or db_list. just use only db_model?
and what is db_model parameter? what will input as this parameter?

**Comment by mrKornWij** [comment]
In pairs from retrieval i use repository that includes all databases and queries(database and query images all are in the same folder)

**Comment by Skydes** [comment]
You should not perform retrieval against other queries.
`python -m hloc.pairs_from_retrieval --descriptors descriptors.h5 --output pairs.txt --num_matched 5 --query_list queries.txt --db_model sfm_model/`
