### ISSUE TITLE
Errors during reconstruction

### ISSUE THREAD

**Issue by jedcheng** [cvg/Hierarchical-Localization#145]
Hi and thanks for the project. 

I have been trying the provided notebooks recently. However, there seems to be a problem with the main function in reconstruction. I saw a similar problem in #116 . I attempted to revert to the suggested commits as well as the commit by the time when it was working for that user. However, all the attempts returned the same error.

 
![image](https://user-images.githubusercontent.com/28983790/149669022-58bdb234-3c99-49c1-99e9-7f5e3d257ae4.png)

**Comment by Skydes** [comment]
This can happen if the code crashes or is interrupted when writing to the database and before changes are committed, because SQLite only accepts one simultaneous write. Did you encounter any other crash before running this cell? The only solution is to restart the kernel. I don't think that `sqlite3` provides any mechanism to prevent this state in case of crash.

**Comment by jedcheng** [comment]
Thanks for the reply.

I have successfully compiled pycolmap locally and ran the scripts locally. It appears to be a problem with running SQLite on Azure ML. I will contact Microsoft later.

Sorry for the inconvenience as I should have realized the origin of the problem.
