### ISSUE TITLE
About the eval results on aachen of hfnet

### ISSUE THREAD

**Issue by ghoshaw** [cvg/Hierarchical-Localization#163]
Hi, I wrote a python script to run the hfnet and save the global and local descriptor as in hloc. Then, as in pipeline_aachen, I block out the extractor of local descriptor using superpoint, and set the feature as the path of my hfnet.h5. And I use the default pairs from nvm and default query pairs used netvlad. It should means NV + HFnet local pipeline.  But the results is not very good and far away from the hfnet paper. Is there some error in my pipeline or the hfnet paper has more tricks in 3D model?
my result is 

42.8 / 53.5 / 70.6 | 9.2 / 13.3 / 28.6
but the paper is 
<img width="291" alt="image" src="https://user-images.githubusercontent.com/23494873/155945584-19ea1a29-82d3-401c-89a6-8d526a725c66.png">

**Comment by Skydes** [comment]
The results with hloc should be strictly better. As a reference, [in the README](https://github.com/cvg/Hierarchical-Localization#results) we report results for SuperPoint+NN on Aachen:

| Methods                                                      | Aachen day         | Aachen night       | Retrieval      |
| ------------------------------------------------------------ | ------------------ | ------------------ | -------------- |
| [SuperPoint + NN](https://www.visuallocalization.net/details/10866/) | 85.4 / 93.3 / 97.2 | 75.5 / 86.7 / 92.9 | NetVLAD top 30 |

They are strictly better than the NV+SP baseline in the original HF-Net paper, partly due to retrieving a higher number of images (20 instead of 10). In HF-Net we average the descriptors of all observations of each 3D point, but this should not matter much.

**Comment by Skydes** [comment]
The results with hloc should be strictly better. As a reference, [in the README](https://github.com/cvg/Hierarchical-Localization#results) we report results for SuperPoint+NN on Aachen:

| Methods                                                      | Aachen day         | Aachen night       | Retrieval      |
| ------------------------------------------------------------ | ------------------ | ------------------ | -------------- |
| [SuperPoint + NN](https://www.visuallocalization.net/details/10866/) | 85.4 / 93.3 / 97.2 | 75.5 / 86.7 / 92.9 | NetVLAD top 30 |

They are strictly better than the NV+SP baseline in the original HF-Net paper, partly due to retrieving a higher number of images (20 instead of 10). In HF-Net we average the descriptors of all observations of each 3D point, but this should not matter much. Note that the ground truth poses of Aachen were updated in the meantime, so there might remain some small inconsistencies.

**Comment by ghoshaw** [comment]
ok, thanks!
