### ISSUE TITLE
Is  pipeline_SfM.ipynb worked for HFNet?

### ISSUE THREAD

**Issue by lmz-whu** [cvg/Hierarchical-Localization#3]
Thanks for your great works! And sorry to bother you.
I'm fellowing your previous work [HFNet](https://github.com/ethz-asl/hfnet). Now I want to build a new SfM model with my own dataset images, using pipeline_SfM.ipynb scripts. Can this SfM model be used by HFNet?
And can I do the matching and image retrival using HFNet?
Thanks

**Comment by Skydes** [comment]
Yes, this is possible.
1. You can either write an interface for HFNet in the [extractors](https://github.com/cvg/Hierarchical-Localization/tree/master/hloc/extractors) (create a TF sessions, load the model, convert the input from PyTorch to numpy and the predictions back - it's a bit hacky) or export yourself the local features into an HDF5 as explained [here](https://github.com/cvg/Hierarchical-Localization#using-your-own-local-features-or-matcher).
2. For image retrieval there is no interface so you need to export into HDF5 as well, as described [here](https://github.com/cvg/Hierarchical-Localization#using-your-own-image-retrieval).

**Comment by kxhit** [comment]
Hi! @Skydes  Thanks for your work!
I'm also turning here from HFnet. For the image retrieval part, we need a HDF5 file with global features (e.g. NetVLAD, HFnet). I find that the .npz files have been generated by HFnet. Is there possible to convert these .npz files to the HDF5 file, so that I can avoid writing new interface for HFnet. Thus I can use HFnet to generate global features, get HDF5 file, and then use this project to get pairs .txt and do the later things.
If that is possible, how to implement the script to convert these .npz files to a HDF5? Could you help me with this?  Thanks a lot!

**Comment by Skydes** [comment]
[This](https://github.com/cvg/Hierarchical-Localization/blob/master/hloc/extract_features.py#L152) is an example of writing to a HDF5 file: for each image create a group, and create a dataset (that's the HDF5 naming) within this group. [This](https://github.com/cvg/Hierarchical-Localization/blob/master/hloc/pairs_from_retrieval.py#L38) is how the global descriptor is read. The dataset should be called `global_descriptor` and contain a D-dimensional numpy array. You can loop over the npz files to pack them into a HDF5 file, or simple modify the export code to write to a single HDF5 file.

**Comment by kxhit** [comment]
Sorry for the late reply. Thanks for your guidance and this is doable. I notice that you get SOTA results in the current ECCV20 workshop challenge. Congrats! Hopefully we will have more datasets supported by this repo! Looking forward to the updates!!!

**Comment by Skydes** [comment]
I will indeed extend the support to others datasets very soon. Stay tuned!
