### ISSUE TITLE
Running in real time

### ISSUE THREAD

**Issue by PKehnel** [cvg/Hierarchical-Localization#36]
Thanks again for your work, was able to build a nice pipeline myself on top of it, using it for my AR application.  
My goal is to run the process in real time, or at least as fast as possible.

So my question is, which parameters can I adjust to gain speed and maybe lose some precision as trade off ...
The options I considered so far: 

1. Chaning values in: _extract feature confs_, fiddling with 'nms_radius': 4 the keypoint_threshold': 0.005 and lowering 'max_keypoints': 512,
2. _matcher confs_, adjusting the 'sinkhorn_iterations': 5 and also the 'match_threshold': 0.2.

Are there other factors I could change? Maybe preloading the model to RAM or building the model with lesser number of images. 

Thanks for your help again! And have a nice christmas.

**Comment by Skydes** [comment]
To speed up the query localization, here are some directions:
1. Faster feature extraction by
   1. Reducing the size of the input images with `resize_max` (e.g. to 512 pixels)
   2. Running SuperPoint with the PyTorch JIT by first tracing it [(example here in Python and C++)](https://github.com/magicleap/SuperGluePretrainedNetwork/compare/master...valgur:cpp-demo)
2. Faster matching by
   1. Reducing the number of keypoints by adjusting `nms_radius`, `keypoint_threshold`, and `max_keypoints`.
   2. Faster SuperGlue inference by reducing the number of Sinkhorn iterations or tracing it [(same example as above)](https://github.com/magicleap/SuperGluePretrainedNetwork/compare/master...valgur:cpp-demo)
   3. Decreasing the number of retrieved images to match (in easy environment 1 or 2 can be sufficient)
   4. Switching to the nearest neighbor matcher (instead of SuperGlue) for easy scenarios
   
Avoid writing the query local features to disk and prefer keeping them in RAM as they can be pretty large. Of course pre-loading the 3D SfM model to RAM will also help. Overall I recommend to measure the runtime of each step to isolate bottlenecks.
