### ISSUE TITLE
superpoint_inloc uses superglue with outdoor weights

### ISSUE THREAD

**Issue by jytime** [cvg/Hierarchical-Localization#392]
Hi Team,

In the example of [pipeline_InLoc](https://github.com/cvg/Hierarchical-Localization/blob/master/pipeline_InLoc.ipynb), we are using 

```
feature_conf = extract_features.confs["superpoint_inloc"]
matcher_conf = match_features.confs["superglue"]
```
where the default dict for "superglue" is

```
    "superglue": {
        "output": "matches-superglue",
        "model": {
            "name": "superglue",
            "weights": "outdoor",
            "sinkhorn_iterations": 50,
        },
    },

```

Is this a bug or specially designed? Should we change it to below?

```
feature_conf = extract_features.confs["superpoint_inloc"]
matcher_conf = match_features.confs["superglue"]
matcher_conf['model']['weights'] = "indoor"
```

**Comment by sarlinpe** [comment]
I recommend not using the SuperGlue's outdoor weights for anything else than ScanNet-like data (low res, motion blur, low texture, no illumination changes). For any other data, including IncLoc (higher res, high texture, illumination changes due to different cameras), I think that the outdoor model works better.
