### ISSUE TITLE
Feature and match files for detection-free algorithms

### ISSUE THREAD

**Issue by ufukefe** [cvg/Hierarchical-Localization#59]
Hi, thanks for your great work!

I want to ask that how I should organize feature and match files for algorithms like [NCNet](https://papers.nips.cc/paper/2018/file/8f7d807e1f53eff5f9efbe5cb81090fb-Paper.pdf)  and [Patch2Pix](https://arxiv.org/pdf/2012.01909.pdf)  which do not have external detection step. 

Excuse me if I am wrong (I do not use the hloc yet, but I am planning to do), I guess I should prepare these files like this way:

For InLoc dataset, for example, let's say I have a query image Q1 and its corresponding NetVLAD pairs {D1,D2,...,D40} from database images, and I have different matches for every pair Q1-D1, Q1-D2... these are outputs of the above-mentioned algorithms.

So, should I arrange the feature file for Q1 as the union of all matched points in the query image for each corresponding database image? After that, should I prepare the match file accordingly?

**Comment by Skydes** [comment]
Hi @ufukefe,
It is not trivial to do SfM 3D reconstruction with dense matching, because there is no notion of track. I am not aware of any right way of doing this. It seems that Patch2Pix groups neighboring pixels together into a single track. This is explained in Section C of [the paper](https://arxiv.org/pdf/2012.01909.pdf). The authors have a fork of hloc [here](https://github.com/GrumpyZhou/Hierarchical-Localization/tree/extend_base_dev), but I haven't tried it out.
