### ISSUE TITLE
‘IntegrityError: UNIQUE constrint failed:cameras.camera_id’ 

### ISSUE THREAD

**Issue by gavinbai** [cvg/Hierarchical-Localization#6]
Hi ,guys, I met this porblem ‘IntegrityError: UNIQUE constrint failed:cameras.camera_id’ when i ran pipeline_Aachen.ipynb，did someone else  meet the same problem？ How to solve  this problem？ Thx。

**Comment by Skydes** [comment]
This happens when creating a new camera in a SQL database but the camera already exists. This can happen if the reconstruction or triangulation failed, and you relaunched without deleting the working directory. Solution: delete `outputs/aachen/sfm_superpoint+superglue` and run the triangulation again.

**Comment by gavinbai** [comment]
yeah， i did   as  you said， the  problem solved。thank  you！
