### ISSUE TITLE
Reconstruction using less than 15 matches per image pair

### ISSUE THREAD

**Issue by tudipffmgt** [cvg/Hierarchical-Localization#66]
I am using `reconstruction.main()` to generate a COLMAP database file from .h5 files I created myself.
For some of the image pairs I use handpicked feature points and have sometimes less than 15 matching points between some image pairs. These are not considered for geometric verfication when I am using your pipeline. 
I also checked the .h5 files and the keypoints are included in these file but get neglected when calling `reconstruction.main()`.

At the moment I am calling the function below and tried to change `min_num_matches` but this had no effect
```
reconstruction.main(
   sfm_dir,
   images,
   sfm_pairs,
   outputs / my_h5_feature_file,
   outputs / my_h5_match_file,
   colmap_path=colmap.exe,
   min_num_matches=0)
```

The result in COLMAP looks like this:
![Matches](https://user-images.githubusercontent.com/46675239/117653841-386f6500-b195-11eb-8e05-1f990511d80a.JPG)

How can I relax the constraint (as I am using only true matches) using a minimum of 15 points in your code? I did not find where to change this parameter.

**Comment by Skydes** [comment]
1. What happens if you skip the geometric verification? It is not needed if you already have outlier-free correspondences. Use `skip_geometric_verification=True`.
2. The geometric verification is based on COLMAP `matches_importer`, which has a default argument `--SiftMatching.min_num_inliers 15` (ignore the SiftMatching term). Did you try to decrease it?

**Comment by tudipffmgt** [comment]
Thanks for the reply. Both approaches work!
