### ISSUE TITLE
some questions about the localization 

### ISSUE THREAD

**Issue by zhengshunkai** [cvg/Hierarchical-Localization#70]
hello,i want to do hloc by my own datas and by the follow steps:
1.my datas:pictures,a fixed camera intrinsics,the true pose from RTK
2.build the sfm model by the triangulation
![image](https://user-images.githubusercontent.com/9248030/121625409-05770480-caa6-11eb-92af-279874f56444.png)
![image](https://user-images.githubusercontent.com/9248030/121625472-1aec2e80-caa6-11eb-9b11-3c0c3f34dceb.png)
3.use the sfm model to do hloc in your frame
![image](https://user-images.githubusercontent.com/9248030/121625543-3a835700-caa6-11eb-82a2-2422d374b05d.png)

The sfm model  and  the best matchs in the hloc process seems right ;but the error between the result of the hloc and RTK seems very big,large than 0.8m.What might be the reason? thank you very much.

**Comment by Skydes** [comment]
Sorry for the late reply. Since the keypoint detection is always somewhat noisy, some errors in the pose can be expected. Such errors grow when the 3D structure is more distant from the camera, as in the image pair that you show here. To reduce these errors, you can try to extract the keypoints at a higher resolution (even by upsampling the images).

**Comment by zhengshunkai** [comment]
Yes,you are right,The main reason is that the noise of the feature points in the distance is large .Thank you very much for your reply.
