### ISSUE TITLE
SfM reconstruction failed

### ISSUE THREAD

**Issue by JosephChenHM** [cvg/Hierarchical-Localization#81]
Hi

I try the latest docker image and run the `pipeline_SfM.ipynb`.
Everything looks good until reconstruction step. I only use 30 image for reproducing reconstruction error.
Here is error message
![image](https://user-images.githubusercontent.com/10712297/128837582-e0d8bdb8-4f73-43f5-a124-030fefae5bbf.png)
Thanks for your time!

**Comment by Skydes** [comment]
Thanks for reporting this! I just pushed to master a fix that prevents crashing when the reconstruction fails. This however does not explain why it fails. Can you share the colmap logs printed in the Jupyter console?

**Comment by JosephChenHM** [comment]
I think there are no matches found.
I ran docker without any GPU support. The script seems to use GPU for matching.
Is it possible to reconstruct the model with only CPU support on docker?
![image](https://user-images.githubusercontent.com/10712297/128889597-b698685a-dd95-4f90-9647-ac311da28390.png)
Thanks for quick reply

**Comment by Skydes** [comment]
Could you please post the full log, including the match importer? It is possible that the match importer is silently failing because of the lack of GPU. Could you please add the flag `--SiftMatching.use_gpu 0` [to the geometric verification in triangulation.py](https://github.com/cvg/Hierarchical-Localization/blob/master/hloc/triangulation.py#L112-L118)? See issue https://github.com/cvg/Hierarchical-Localization/issues/65 for reference.
