### ISSUE TITLE
PyColmap issue while building Docker Image

### ISSUE THREAD

**Issue by KanishAnand** [cvg/Hierarchical-Localization#94]
Hi,

I am trying to build docker image locally using the following steps:
```
git clone --recursive https://github.com/cvg/Hierarchical-Localization/
cd Hierarchical-Localization/
git submodule update --init --recursive
docker build -t hloc:latest .
```

But docker build operation failed with the error:   **Failed building wheel for pycolmap**
Attaching detailed error logs [here](https://pastebin.pl/view/22afe3ba)

Can you please help me with this?

**Comment by Skydes** [comment]
Hi, thanks for reporting this issue. Unfortunately we recently pushed a new feature to pycolmap which depends on a recent change to COLMAP. Two solutions:
1. Build a new Docker image from the updated dev branch: https://github.com/colmap/colmap/tree/dev/docker
2. Revert pycolmap to [a previous state](https://github.com/mihaidusmanu/pycolmap/tree/fe5b30345d5de31f9376675c68f19348149426b0) by updating our `requirements.txt` to
```
git+https://github.com/mihaidusmanu/pycolmap@fe5b30345d5de31f9376675c68f19348149426b0
```
Sorry about the inconvenience, we will consider pushing an updated Docker image.

**Comment by Shubodh** [comment]
Thanks a lot for the quick reply, @Skydes. We tried option 2 and it is working now!

**Comment by hhmaizi** [comment]
thanks a lot for this great project. When using the Installation method, [Installation](https://github.com/cvg/Hierarchical-Localization#installation), facing the same probelm. How could I assign specific commits of pycolmap for setup.py? tried to modify setup.py

> 
'pycolmap @ git+https://https://github.com/mihaidusmanu/pycolmap@fe5b30345d5de31f9376675c68f19348149426b0#egg=pycolmap-0'

but it fails. Appreciate it if you provide the right syntax to modify setup.py. @Skydes

**Comment by Skydes** [comment]
@hhmaizi How does it fail? Adding the commit tag works well on my end:
```diff
-   'pycolmap @ git+https://github.com/mihaidusmanu/pycolmap',
+   'pycolmap @ git+https://github.com/mihaidusmanu/pycolmap@fe5b30345d5de31f9376675c68f19348149426b0',
```

**Comment by ted8201** [comment]
Sorry, it's caused by my careless. I build pycolmap manually, yestoday. And found that I should build comap first for pycolmap to work. The Error below mislead me. Thanks again for the immediate response, really appreciate that.
`ERROR: Could not find a version that satisfies the requirement pycolmap (unavailable) (from hloc) (from versions: 0.0.1)
ERROR: No matching distribution found for pycolmap (unavailable)`

**Comment by ted8201** [comment]
@Skydes , Sorry, it's caused by my careless. I build pycolmap manually, yestoday. And found that I should build comap first for pycolmap to work. The Error below mislead me. Thanks again for the immediate response, really appreciate that.
`ERROR: Could not find a version that satisfies the requirement pycolmap (unavailable) (from hloc) (from versions: 0.0.1) ERROR: No matching distribution found for pycolmap (unavailable)`

**Comment by Skydes** [comment]
This should be solved in the last release https://github.com/cvg/Hierarchical-Localization/pull/136.
